//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTS_By_Asmita
{
    public partial class TheaterShows
    {
        /// <summary>
        /// GridViewShows control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridViewShows;
        
        /// <summary>
        /// SqlDataSourceShowsByTheater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceShowsByTheater;
        
        /// <summary>
        /// lblNoShows control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoShows;
    }
}
